@startuml
skinparam legendBackgroundColor #fff8db

legend top right
    Project   BI_PYTHON_AZURE
    Author    Mélodie Ohan
    Version   10-01-2022
endlegend

title Class Diagram
package interface {
  Interface IDataObject {
    + doesExist(objectName: string): bool
    + create(objectName: string, localFilePath: string)
    + download(objectName: string): byte[]
    + publish(objectName: string): string 
    + delete(objectName: string, recursive = false: bool): void
  }
}

package config {
  Class AzureClient {
    - serviceClient: BlobServiceClient
    + AzureClient()
    + getBlobServiceClient(): BlobServiceClient
    + getContainerClient(containerName: string): ContainerClient
    + getBlobClient(containerName: string, blobName: string): BlobClient 
  }

  Class AzureConfig {
    - {static} connectionStringEnvKey: string
    - connectionString: string
    + AzureConfig()
    + <get> connectionString(): string
  } 
}


package blob {
  Class BlobHelper {
    - storageClient: AzureClient
    - containerName: string
    + doesExist(blobName: string): bool
    + create(blobName: string, localFilePath: string)
    + download(blobName: string): bytes
    + publish(blobName: string): string 
    + delete(blobName: string): void 
  }
}

package container {
  Class ContainerHelper {
    - storageClient: AzureClient
    + doesExist(containerName: string): bool
    + create(containerName: string, localFilePath: string)
    + download(containerName: string): byte
    + publish(containerName: string): string 
    + delete(containerName: string): void 
  }
}

IDataObject <|--- BlobHelper
IDataObject <|--- ContainerHelper
ContainerHelper -> "1" BlobHelper
BlobHelper --> "1" AzureClient
ContainerHelper --> "1" AzureClient
AzureClient --> "1" AzureConfig
