name: CI/CD pipeline

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

env:
  CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up env file
      run: |
        touch secret.settings.env
        echo "AZURE_STORAGE_CONNECTION_STRING=${{ env.CONNECTION_STRING }}" >> secret.settings.env
    - name: Build tests container
      run: docker build . --tag bi_python_azure-tests --file Dockerfile --target tests
    - name: Run tests
      run: docker run --env-file secret.settings.env bi_python_azure-tests:latest
