name: CI/CD pipeline

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

env:
  CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up env file
      run: |
        echo "AZURE_STORAGE_CONNECTION_STRING=${{ env.CONNECTION_STRING }}" >> secret.settings.env

    - name: Build Production
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.PROJECT_NAME }}:production

    - name: Deploy
      uses: docker/compose-action@v1
      with:
        command: up
        compose-file: docker-compose.yml
        env-file: secret.settings.env
